#!/bin/bash
# 
# Shared shell library for test management 
# 
# Copyright (C) 2016 - 2020, chenliangfei Limited. 
# 
# This program is free software; you can redistribute it and/or 
# modify it under the terms of the GNU General Public License 
# as published by the Free Software Foundation; either version 2 
# of the License, or (at your option) any later version. 
# 
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details. 
# 
# You should have received a copy of the GNU General Public License 
# along with this program; if not, write to the Free Software 
# Foundation, Inc.,Shenzhen, China
# 
# Author: chenliangfei <liangfei2015@foxmail.com> 



# config file
CONFIG_INFO="config/auto_sas_test.ini"
# FIO tools config file
FIO_CONFIG="config/fio.conf"

# log file
INFO_LOG="log/auto_sas_test.log"
ERROR_INFO="log/error_info.log"

# D03
PHY_ADDR_VALUE=("0xa2002000" "0xa2002400" "0xa2002800" "0xa2002c00" "0xa2003000" "0xa2003400" "0xa2003800" "0xa2003c00")
# fio tools IO size
FIO_BS=("4M" "4K" "512K" "512B")

## auto_function_test.sh script configuration item.
#
is_insmod_and_rmmod_module=`cat $CONFIG_INFO | grep -w "^is_insmod_and_rmmod_module" | awk -F '=' '{print $2}'`
mod_version=`cat $CONFIG_INFO | grep -w "^mod_version" | awk -F '=' '{print $2}'`
mod_v1_file=`cat $CONFIG_INFO | grep -w "^mod_v1_file" | awk -F '=' '{print $2}'`
mod_v2_file=`cat $CONFIG_INFO | grep -w "^mod_v2_file" | awk -F '=' '{print $2}'`
mod_main_file=`cat $CONFIG_INFO | grep -w "^mod_main_file" | awk -F '=' '{print $2}'`
#
is_hard_reset=`cat $CONFIG_INFO | grep -w "^is_hard_reset" | awk -F '=' '{print $2}'`
hard_reset_file_name=`cat $CONFIG_INFO | grep -w "^hard_reset_file_name" | awk -F '=' '{print $2}'`
#
is_link_reset=`cat $CONFIG_INFO | grep -w "^is_link_reset" | awk -F '=' '{print $2}'`
link_reset_file_name=`cat $CONFIG_INFO | grep -w "^link_reset_file_name" | awk -F '=' '{print $2}'`
#
is_inquire_open_close_phy_info=`cat $CONFIG_INFO | grep -w "^is_inquire_open_close_phy_info" | awk -F '=' '{print $2}'`
#
is_disk_negotiated_link_rate_file_name=`cat $CONFIG_INFO | grep -w "^is_disk_negotiated_link_rate_file_name" | awk -F '=' '{print $2}'`
disk_negotiated_link_rate_query=`cat $CONFIG_INFO | grep -w "^disk_negotiated_link_rate_query" | awk -F '=' '{print $2}'`
disk_negotiated_link_rate_file_name=`cat $CONFIG_INFO | grep -w "^disk_negotiated_link_rate_file_name" | awk -F '=' '{print $2}'`
disk_negotiated_link_rate_value=`cat $CONFIG_INFO | grep -w "^disk_negotiated_link_rate_value" | awk -F '=' '{print $2}'`
#
is_key_words_query=`cat $CONFIG_INFO | grep -w "^is_key_words_query" | awk -F '=' '{print $2}'`
#
is_fio_run_close_all_phy=`cat $CONFIG_INFO | grep -w "^is_fio_run_close_all_phy" | awk -F '=' '{print $2}'`
close_all_phy_fio_disk=`cat $CONFIG_INFO | grep -w "^close_all_phy_fio_disk" | awk -F '=' '{print $2}'`
close_all_phy_fio_time=`cat $CONFIG_INFO | grep -w "^close_all_phy_fio_time" | awk -F '=' '{print $2}'`
#
is_fio_run_enable_disk=`cat $CONFIG_INFO | grep -w "^is_fio_run_enable_disk" | awk -F '=' '{print $2}'`
fio_enable_disk=`cat $CONFIG_INFO | grep -w "^fio_enable_disk" | awk -F '=' '{print $2}'`
fio_enable_time=`cat $CONFIG_INFO | grep -w "^fio_enable_time" | awk -F '=' '{print $2}'`
fio_run_enable_file=`cat $CONFIG_INFO | grep -w "^fio_run_enable_file" | awk -F '=' '{print $2}'`


## auto_performanxe_test.sh script configuration item.
#
is_disk_data_comprehensive_test=`cat $CONFIG_INFO | grep -w "^is_disk_data_comprehensive_test" | awk -F '=' '{print $2}'`
fio_comprehensive_test_time=`cat $CONFIG_INFO | grep -w "^fio_comprehensive_test_time" | awk -F '=' '{print $2}'`
fio_comprehensive_test_IO_size=`cat $CONFIG_INFO | grep -w "^fio_comprehensive_test_IO_size" | awk -F '=' '{print $2}'`
Disk_file_consistency_test_count=`cat $CONFIG_INFO | grep -w "^Disk_file_consistency_test_count" | awk -F '=' '{print $2}'`
#
is_runing_fio_link_reset=`cat $CONFIG_INFO | grep -w "^is_runing_fio_link_reset" | awk -F '=' '{print $2}'`
runing_fio_link_reset_disk=`cat $CONFIG_INFO | grep -w "^runing_fio_link_reset_disk" | awk -F '=' '{print $2}'`
runing_fio_link_reset_time=`cat $CONFIG_INFO | grep -w "^runing_fio_link_reset_time" | awk -F '=' '{print $2}'`
runing_fio_link_reset_file_name=`cat $CONFIG_INFO | grep -w "^runing_fio_link_reset_file_name" | awk -F '=' '{print $2}'`
#
is_runing_fio_hard_reset=`cat $CONFIG_INFO | grep -w "^is_runing_fio_hard_reset" | awk -F '=' '{print $2}'`
runing_fio_hard_reset_disk=`cat $CONFIG_INFO | grep -w "^runing_fio_hard_reset_disk" | awk -F '=' '{print $2}'`
runing_fio_hard_reset_time=`cat $CONFIG_INFO | grep -w "^runing_fio_hard_reset_time" | awk -F '=' '{print $2}'`
runing_fio_hard_reset_file_name=`cat $CONFIG_INFO | grep -w "^runing_fio_hard_reset_file_name" | awk -F '=' '{print $2}'`
#
is_file_transfer_stability_test=`cat $CONFIG_INFO | grep -w "^is_file_transfer_stability_test" | awk -F '=' '{print $2}'`
file_transfer_stability_test_disk=`cat $CONFIG_INFO | grep -w "^file_transfer_stability_test_disk" | awk -F '=' '{print $2}'`


## auto_pressure_test.sh script configuration item.
#
is_fio_run_phy_frequently_flash=`cat $CONFIG_INFO | grep -w "^is_fio_run_phy_frequently_flash" | awk -F '=' '{print $2}'`
frequently_phy_addr=`cat $CONFIG_INFO | grep -w "^frequently_phy_addr" | awk -F '=' '{print $2}'`
frequently_fio_time=`cat $CONFIG_INFO | grep -w "^frequently_fio_time" | awk -F '=' '{print $2}'`
frequently_fio_disk=`cat $CONFIG_INFO | grep -w "^frequently_fio_disk" | awk -F '=' '{print $2}'`
#
is_reset_link_loop=`cat $CONFIG_INFO | grep -w "^is_reset_link_loop" | awk -F '=' '{print $2}'`
reset_link_loop_more=`cat $CONFIG_INFO | grep -w "^reset_link_loop_more" | awk -F '=' '{print $2}'`
loop_rest_link_file=`cat $CONFIG_INFO | grep -w "^loop_rest_link_file" | awk -F '=' '{print $2}'`
loop_rest_hard_file=`cat $CONFIG_INFO | grep -w "^loop_rest_hard_file" | awk -F '=' '{print $2}'`
#
is_fio_long_time_run=`cat $CONFIG_INFO | grep -w "^is_fio_long_time_run" | awk -F '=' '{print $2}'`
fio_long_run_time=`cat $CONFIG_INFO | grep -w "^fio_long_run_time" | awk -F '=' '{print $2}'`
fio_long_run_disk=`cat $CONFIG_INFO | grep -w "^fio_long_run_disk" | awk -F '=' '{print $2}'`
#
is_fio_loop_run=`cat $CONFIG_INFO | grep -w "^is_fio_loop_run" | awk -F '=' '{print $2}'`
fio_loop_run_time=`cat $CONFIG_INFO | grep -w "^fio_loop_time" | awk -F '=' '{print $2}'`
fio_loop_run_more=`cat $CONFIG_INFO | grep -w "^fio_loop_run_more" | awk -F '=' '{print $2}'`
fio_loop_run_disk=`cat $CONFIG_INFO | grep -w "^fio_loop_run_disk" | awk -F '=' '{print $2}'`
#
is_run_business_repeatedly_disk_enable=`cat $CONFIG_INFO | grep -w "^is_run_business_repeatedly_disk_enable" | awk -F '=' '{print $2}'`
hot_plug_disk_enable_file=`cat $CONFIG_INFO | grep -w "^hot_plug_disk_enable_file" | awk -F '=' '{print $2}'`
hot_plug_disk_file=`cat $CONFIG_INFO | grep -w "^hot_plug_disk_file" | awk -F '=' '{print $2}'`
hot_plug_fio_run_time=`cat $CONFIG_INFO | grep -w "^hot_plug_fio_run_time" | awk -F '=' '{print $2}'`



## Utility function
#
function fail_test()
{
    local reason="$1"
    echo "${TEST}: FAIL - ${reason}"
}

#
function pass_test()
{
    echo "${TEST}: PASS"
}

#
function fdisk_query() 
{
    disk_info=`fdisk -l 2>/dev/null`
	
    if [ x"$disk_info" = x"" ]
    then
        fail_test "Use the \"fdisk -l\" command to query disk failure."
	
        return 1
    fi
}

#
function close_all_phy()
{
    for addr in "${PHY_ADDR_VALUE[@]}"
    do
       devmem2 $addr w 0x06 1>/dev/null 2>&1
    done
}

# open all phy
function open_all_phy()
{
    for addr in "${PHY_ADDR_VALUE[@]}"
    do
        devmem2 $addr w 0x07 1>/dev/null 2>&1
    done
}

# Automatic disk partition
function dev_partition()
{
fdisk $1 << EOF
n
p


+50G
n
p


+50G
w
EOF
}


