#!/bin/bash

# Module test run switch, 1 - open test case, 0 - close test case, Default is 1.
RUN_SAS=1
RUN_XGE=1
RUN_PCIE=1

# IMAGE Configuration item
IMAGE_FILE=common_tool/Image
IMAGE_DIR_PATH=~/tftp

## Common Configuration item
SERVER_IP=
SERVER_USER=
SERVER_PASSWD=
# Single board environment username and password
SYSTEM_USER=root
SYSTEM_PASSWD=root

REPORT_PATH=~/autotest/report
REPORT_FILE=report.csv
AUTOTEST_ZIP_FILE=autotest.tar.gz

# SAS Module Configuration item
SAS_MAIN=sas_autotest/sas_main.sh
SAS_REPORT_FILE=sas_report.csv
SAS_BORADNO=

# XGE Module Configuration item
XGE_MAIN=xge_autotest/xge_main.sh
XGE_REPORT_FILE=xge_report.csv
XGE_BORADNO=
BACK_XGE_BORADNO=

# PCIE Module Configuration item
PCIE_MAIN=sas_autotest/pcie_main.sh
PCIE_REPORT_FILE=pcie_report.csv
PCIE_BORADNO=
BACK_XGE_BORADNO=

