#!/bin/bash
#
#


# Test case mapping table
declare -A case_map=(
#File transfer stability test, on - oepn test case, off - close test case, Default is true.
["test_case_file_name"]="on"

)

# Common tools directory path
COMMON_TOOL_PATH="common_tool"

# Test case code directory path
TEST_CASE_PATH="xge_autotest/str"


