#!/bin/bash
# 


# Load configuration options
. config/sas_test_config

## Utility function
#
function fail_test()
{
    local reason="$1"
    printf "%s: %s - %s\n" "${TEST}" "FAIL" "${reason}"
    echo "${TEST}:  " "FAIL" "${reason}" >> $INFO_LOG
}

#
function pass_test()
{
    printf "%s: %s\n" "${TEST}" "PASS"
    echo "${TEST}:  " "PASS" >> $INFO_LOG
}

#
function get_all_disk_part()
{
    for name in `fdisk -l | grep -o "/dev/[a-z]d[a-z][1-9]"`
    do
        ALL_DISK_PART_NAME[${#ALL_DISK_PART_NAME[*]}]=$name
    done
}
